[package]
name = "p1am_rs"
version = "0.1.0"
edition = "2018"

[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=--nmagic",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "target-cpu=cortex-m33",
]

